start =
	expression

validchar =
	[0-9a-zA-Z_?!+-=@#$%^&*/.]

atom =
	chars:validchar+
		{ return chars.join(""); }

expression =
	list
      / atom
      / quote

spacedexpression =
	" " list:list { return list; }
      / " " atom:atom { return atom; }
      / " " quote:quote { return quote; }

quote =
	"'" list:list { return ["quote", list]; }

list =
	"(" first:expression rest:spacedexpression* ")"
		{ rest.unshift(first); return rest; }
